[tool.pyright]
include = ["pico"]
ignore = ["**/typings"]
exclude = [
    ".*",
    "__*",
    "**/typings",
]
typeCheckingMode = "basic"
stubPath = "typings"
typeshedPath = "typings"
pythonPlatform = "Linux"
reportMissingModuleSource = "none"
reportUnnecessaryTypeIgnoreComment = "error"